mode: 'train_full' # 'train_full', 'only_train', 'only_rec', 'only_prior', 'only_posterior'
dataset: 'MSK-Chord' # ''
GPU: True
seed: 0
train_dir: '/datasets' #   
save_path: '/benchmark/multiNODEs/real_datasets/hyperopt'
optuna_study: 'MSKChord_optuna_MultiNODEs'
                
# Specific training parameters
n_long_var: 2
t_visits: 7306
static_data: True
# z_dim_static: 3
# s_dim_static: 6
solver: 'Normal' # 'Adjoint', 'Normal', 'Julia'
method_solver: 'dopri5' # 'dopri5', 'dopri8', 'bosh3', 'fehlberg2', 'adaptive_heun'
rtol: 1.0e-3
atol: 1.0e-3
step_size_solver: 1.0e-3
type_enc: 'LSTM' # 'RNN', 'LSTM'
type_dec: 'orig' # 'RNN', 'LSTM', 'Orig'
# drop_dec: 0.4951111384939868
act_dec: 'tanh' # 'none', 'tanh', 'relu'
# num_ode_layers: 1 # 1, 2, 3
act_ode: 'tanh' # 'none', 'tanh', 'relu'
act_rnn: 'relu' # 'none', 'relu', 'tanh'
batch_norm_static: True
# batch_size: 0.400910825235765 # in percentage of the dataset
from_best: False
# latent_dim: 1.8837462054054002 # in percentage of the long variables
# lr: 0.001 # 0.001248
# num_epochs: 1900
epoch_init: 1
# nhidden: 4.584466407303982
# rnn_nhidden_dec: 0.6974659448314735
# rnn_nhidden_enc: 0.49866725741363976
scaling_ELBO: 1
# save_freq: 300
print_freq: 50

# Specific simulation parameters
time_max: 1
time_min: 0
time_steps: 7306
s_prob: [] # vector with propability of s during prior sampling
sigma_long: 1
sigma_stat: 1
N_pop: 1
