mode: 'only_train' # 'train_full', 'only_train', 'only_rec', 'only_prior', 'only_posterior'
dataset: 'Physionet_2012' # ''
GPU: True
seed: 0
train_dir: '/datasets' #   
save_path: '/benchmark/multiNODEs/real_datasets/main_bestparam'
exp_name: 'Physionet_2012_final'
n_long_var: 9
t_visits: 2881
from_best: True

# Specific training parameters
num_epochs: 3000
lr: 0.001 #0.0009
static_data: True
z_dim_static: 6
s_dim_static: 7 #7
solver: 'Normal' # 'Adjoint', 'Normal', 'Julia'
method_solver: 'dopri5' # 'dopri5', 'dopri8', 'bosh3', 'fehlberg2', 'adaptive_heun'
rtol: 1.0e-3
atol: 1.0e-3
step_size_solver: 1.0e-3
type_enc: 'LSTM' # 'RNN', 'LSTM'
type_dec: 'orig' # 'RNN', 'LSTM', 'Orig'
drop_dec: 0.088914 # 0.48462328943186767
act_dec: 'relu' #'tanh' # 'none', 'tanh', 'relu'
num_ode_layers: 3 #1 # 1, 2, 3
act_ode: 'tanh' # 'none', 'tanh', 'relu'
act_rnn: 'relu' # 'none', 'relu', 'tanh'
batch_norm_static: True
batch_size: 0.084174 # 0.08110046087098668 # in percentage of the dataset
from_best: False
latent_dim: 0.921016 #0.7027702737271135 # in percentage of the long variables
epoch_init: 1
nhidden: 1.450168 #1.598116550987182
rnn_nhidden_enc: 0.10841 #0.2733796203949324
rnn_nhidden_dec: 0.110221 #0.35146272573439763
scaling_ELBO: 1
save_freq: 300
print_freq: 20

# Specific simulation parameters
time_max: 1
time_min: 0
s_prob: [] # vector with propability of s during prior sampling
sigma_long: 1
sigma_stat: 1
N_pop: 50
time_steps: 2881
