mode: 'only_train' # 'train_full', 'only_train', 'only_rec', 'only_prior', 'only_posterior'
dataset: 'AVE0005' # ''
GPU: True
seed: 0
train_dir: '/datasets' #   
save_path: '/benchmark/multiNODEs/real_datasets/main_bestparam'
exp_name: 'AVE0005_log_scaled'
n_long_var: 23
t_visits: 673

# Specific training parameters
num_epochs: 3000
lr: 0.00297382402105411
static_data: True
z_dim_static: 8
s_dim_static: 3
solver: 'Normal' # 'Adjoint', 'Normal', 'Julia'
method_solver: 'dopri5' # 'dopri5', 'dopri8', 'bosh3', 'fehlberg2', 'adaptive_heun'
rtol: 1.0e-4
atol: 1.0e-4
step_size_solver: 1.0e-3
type_enc: 'LSTM' # 'RNN', 'LSTM'
type_dec: 'orig' # 'RNN', 'LSTM', 'Orig'
drop_dec: 0.08125929819392552
act_dec: 'tanh' # 'none', 'tanh', 'relu'
num_ode_layers: 4 # 1, 2, 3
act_ode: 'tanh' # 'none', 'tanh', 'relu'
act_rnn: 'relu' # 'none', 'relu', 'tanh'
batch_norm_static: True
batch_size: 0.08302734705220324 # in percentage of the dataset
from_best: False
latent_dim: 0.2740576097030532 # in percentage of the long variables
epoch_init: 1
nhidden: 1.3097957490344427
rnn_nhidden_enc: 0.4976719603234085
rnn_nhidden_dec: 0.465662325376476
scaling_ELBO: 1
save_freq: 300
print_freq: 20

# Specific simulation parameters
time_max: 1
time_min: 0
s_prob: [] # vector with propability of s during prior sampling
sigma_long: 1
sigma_stat: 1
N_pop: 50
time_steps: 673
